### ISSUE TITLE
unity 2021 camera inverted

### ISSUE THREAD

**Issue by rudyaa-sd** [CMDRSpirit/URPTemporalAA#6] opened 2022-06-13 20:22 UTC
Hello, when I enable post processing on my camera the camera gets inverted whenever I'm adding the TAA camera script to it

**Comment by CMDRSpirit** [comment] 2022-06-14 07:07
What do you mean with inverted, can you share a screenshot?
If your image is flipped upside down, you can try inverting the y-coordinate in the shader for the first  `tex2D` call.
You can do that by replacing `i.uv` with `float2(i.uv.x, 1 - i.uv.y)`.
https://github.com/CMDRSpirit/URPTemporalAA/blob/384da583d795e4aa41f43833f1823a4c42c8a81b/TemporalAA/TemporalAAShader.shader#L139

**Comment by damagefilter** [comment] 2022-07-06 08:15
Hello!

Thanks for sharing your TAA implementation. It's really really nice.

Sadly, I get the same issue but inversing the y coordinate will result in a number of artifacts.

![image](https://user-images.githubusercontent.com/1213756/177502232-651cf2bb-c788-469f-a30f-9b2d45c02f16.png)

I also attempted to inverse the Y value in the vertex program. With a similar result.

I wish my shader-foo would be better so I could be of more help or even provide a solution - as I have the feeling it's probably something comparatively simple. Alas, I suck at shader programming :c

**Comment by CMDRSpirit** [comment] 2022-07-08 07:36
That is really weird. What graphics API are you using? It may be that the framebuffer access in OpenGL / Vulkan is different to DirectX. I think I need to look into how to include those SRP texture functions into the shader.

BTW: I cannot see any artifacts without having a reference image ;)
It is clear however that the edges are not anti-aliased.

**Comment by damagefilter** [comment] 2022-07-12 12:10
Ah, this is a good point.
Let me fix that.
So this is with TAA and unflipped y coordinate. I tried with Vulkan and DX 11, both are flipped.
OpenGLCore and ES2/3 are not flipped but require slightly different config.
![image](https://user-images.githubusercontent.com/1213756/178485362-6b3120ac-1c50-4f29-b282-a305cd171738.png)

And when I flip the y coordinate in the vertex program like so:
```hlsl
v2f vert (appdata v)
{
    v2f o;
    o.vertex = UnityObjectToClipPos(v.vertex);
    o.uv = float2(v.uv.x, 1 - v.uv.y);
    return o;
}
```
This is taken with Vulkan, same results with DX 11.
![image](https://user-images.githubusercontent.com/1213756/178485891-07f13a7f-7948-471e-81f7-6099a56e1377.png)

So definitely something with the graphics APIs.
I think it's strange that it would create these artifacts when flipping the y coordinate.
But even more so I wonder what they could possibly have changed to make it break between 2020 and 2021 LTS

**Comment by CMDRSpirit** [comment] 2022-07-23 09:46
Okay, that looks really weird. It makes no sense to me why there is a 'halo' of some sort around the objects. I will try to do some tests when I have time the next weeks, but I'm currently a bit busy :/
First, I have to reproduce these artifacts somehow, because it works in my projects with DX and VK.

**Comment by damagefilter** [comment] 2022-09-28 14:08
I've had some time for fiddling with this again and figured it somehow has to do with the post processing volumes.
If you turn post processing off in the renderer or on the camera, it will unflip the final image.

Likewise if you (with post processing enabled) enable FXAA on the camera, it will also unflip the final image.

That's in the current 2021.3.10 LTS. Don't know what it means but I thought I might as well share.

I also been poking at the shader a little and found that the image rendered when the UVs are flipped is 100% the contens of `lastCol` which is, presumably, why it looks weird.

Edit: Figured, by above observation, it had to be something on the line that lerps `lastCol` and `curCol`.

https://github.com/CMDRSpirit/URPTemporalAA/blob/384da583d795e4aa41f43833f1823a4c42c8a81b/TemporalAA/TemporalAAShader.shader#L178

The only moving parts in there being `pos` and `temporalUV` - the latter being calculated based on `pos` ... that leaves `pos` as possible suspect. 
Poking at it, I used the unflipped UV to calculate it. Something like so:
```hlsl
// in frag()

float2 unflippedUv = i.uv; // use for pos
i.uv = float2(i.uv.x, 1 - i.uv.y); // use for sampling _MainTex
float3 pos = float3(unflippedUv * 2.0 - 1.0, 1.0);
```

This produces correct results. Of course it's not a fix because turning off post processing will now flip the final image back up.
But it's something.

**Comment by CMDRSpirit** [comment] 2022-10-01 10:53
Wow, thank you for your research on that topic :)
I think I will just include a checkbox to toggle between both versions and hopefully we can close this issue then.

**Comment by CMDRSpirit** [comment] 2022-10-01 11:59
I've pushed a solution that adds a toggle button for your code path to the TAA feature.
https://github.com/CMDRSpirit/URPTemporalAA/blob/8476a9d977e0e5e6925d256eb152818276bbd45c/TemporalAA/TemporalAAFeature.cs#L37
Would be great if you can test this fix @damagefilter.

**Comment by damagefilter** [comment] 2022-10-04 08:52
Can confirm. It is working this way.

I have one more idea I'd like to put forth in this regard which deals with auto detecting if flipping is required or not.
But it doesn't necessarily pertain to this issue. I think it's okay to close it.

I'll prepare a PR later, when I found what I was looking for - and then you can see wether you want it :)

**Comment by CMDRSpirit** [comment] 2022-10-04 17:16
Perfect, thank you :)
BTW, my other idea was to use the `SAMPLE_TEXTURE2D` macro that should be available through SRP, but I have to dig deeper into that stuff before being able to use it.

**Closed as completed by CMDRSpirit** 2022-10-04 17:16 UTC
